### ISSUE TITLE
replace label with div

### ISSUE THREAD

**Issue by MariMax** [NikaOrl/next-checkbox#16]
https://github.com/NikaOrl/next-checkbox/blob/master/projects/next-checkbox/src/lib/next-checkbox.component.html#L1

**Comment by MariMax** [comment]
Probably won't work, as Maria pointed out, but one minor thing can be improved, set all the paddings to 0, except of left one

**Comment by NikaOrl** [comment]
@MariMax as I see, you've already set all the paddings to 0 in the "adds some fixes" PR so this issue is not actual now, right?
For other ones, I'll add new PR tomorrow (I also want to change code style according to the files that you've sent before)

**Comment by MariMax** [comment]
addressed here #19
